import { IActivity } from "./IActivity";
export const ACTIVITIES: IActivity[] = [
    { id: 1,/*gameUrl: '1231'*/ name: 'Chevrolet', category: 'Onix Premiere', description: 'Onix Premiere', image: new URL("https://www.megautos.com/wp-content/uploads/2019/10/chevrolet-onix-premier-2020-dinamica.jpg"), selected: false},
    { id: 2,/*gameUrl: '1232'*/ name: 'Chevrolet', category: 'Onix Premiere',  description: 'Onix Premiere', image: new URL("https://www.megautos.com/wp-content/uploads/2019/10/chevrolet-onix-premier-2020-dinamica.jpg"), selected: false},
    { id: 3,/*gameUrl: '1233'*/ name: 'Chevrolet', category: 'Onix Premiere',  description: 'Onix Premiere', image: new URL("https://www.megautos.com/wp-content/uploads/2019/10/chevrolet-onix-premier-2020-dinamica.jpg"), selected: false},
    { id: 4,/*gameUrl: '1234'*/ name: 'Chevrolet', category: 'Onix Premiere',  description: 'Onix Premiere', image: new URL("https://www.megautos.com/wp-content/uploads/2019/10/chevrolet-onix-premier-2020-dinamica.jpg"), selected: false},
    { id: 5,/*gameUrl: '1235'*/ name: 'Chevrolet', category: 'Onix Premiere',  description: 'Onix Premiere', image: new URL("https://www.megautos.com/wp-content/uploads/2019/10/chevrolet-onix-premier-2020-dinamica.jpg"), selected: false},
    { id: 6,/*gameUrl: '1236'*/ name: 'Chevrolet', category: 'Onix Premiere',  description: 'Onix Premiere', image: new URL("https://www.megautos.com/wp-content/uploads/2019/10/chevrolet-onix-premier-2020-dinamica.jpg"), selected: false},
    { id: 7,/*gameUrl: '1237'*/ name: 'Chevrolet', category: 'Onix Premiere',  description: 'Onix Premiere', image: new URL("https://www.megautos.com/wp-content/uploads/2019/10/chevrolet-onix-premier-2020-dinamica.jpg"), selected: false},
    { id: 8,/*gameUrl: '1238'*/ name: 'Chevrolet', category: 'Onix Premiere',  description: 'Onix Premiere', image: new URL("https://www.megautos.com/wp-content/uploads/2019/10/chevrolet-onix-premier-2020-dinamica.jpg"), selected: false},
    { id: 9,/*gameUrl: '1239'*/ name: 'Chevrolet', category: 'Onix Premiere',  description: 'Onix Premiere', image: new URL("https://www.megautos.com/wp-content/uploads/2019/10/chevrolet-onix-premier-2020-dinamica.jpg"), selected: false},
    { id: 10,/*gameUrl:'1210'*/ name: 'Chevrolet', category: 'Onix Premiere',  description: 'Onix Premiere', image: new URL("https://www.megautos.com/wp-content/uploads/2019/10/chevrolet-onix-premier-2020-dinamica.jpg"), selected: false},
];